chore: Add missing dependencies
    from rich.traceback import install as install_rich_traceback
ModuleNotFoundError: No module named 'rich'

  ❱  15 from cyclopts import App, Parameter                    │
ModuleNotFoundError: No module named 'cyclopts'

Change-Id: Ia3fa3e8d0cd2a58bbe4a1794d4203c9089ebf22b
Signed-off-by: Sushrut1101 <guptasushrut@gmail.com>